theme = "molokai"

[editor]
bufferline = "always"
cursorline = true
scrolloff = 10
true-color = true
undercurl = true
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "error"

[keys.normal]
"tab" = "goto_next_buffer"
"S-tab" = "goto_previous_buffer"
"C-x" = ":buffer-close"

[keys.insert]
"C-[" = "normal_mode"

[keys.select]
"C-[" = "normal_mode"
