theme = "molokai"

[editor]
bufferline = "always"
cursorline = true
true-color = true

[editor.cursor-shape]
insert = "block"

[editor.indent-guides]
render = true

[keys.normal]
"tab" = "goto_next_buffer"
"S-tab" = "goto_previous_buffer"

[keys.insert]
"C-[" = "normal_mode"
