[language-server.jdtls]
command = "jdtls"

[language-server.gpt]
command = "helix-gpt"

[language-server.vscode-json-languageserver]
command = "vscode-json-languageserver"
args = ["--stdio"]

[[language-server.typescript-language-server.config.plugins]]
name = "@vue/typescript-plugin"
location = "/nix/store/3ihrs9w5yvfl6g7ib3mmw9i70mplcmmz-vue-language-server-2.1.6/lib/node_modules/@vue/language-server"
languages = ["vue"]

[[language]]
name = "vue"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "vue"] }
language-servers = ["typescript-language-server", "gpt"]

[[language]]
name = "typescript"
formatter = { command = "prettier" }
language-servers = ["typescript-language-server", "gpt"]

[[language]]
name = "java"
roots = ["build.gradle"]
language-servers = ["jdtls", "gpt"]

[[language]]
name = "nix"
formatter = { command = "nixpkgs-fmt" }
language-servers = ["nil", "gpt"]

[[language]]
name = "json"
language-servers = ["vscode-json-languageserver", "gpt"]

[[language]]
name = "python"
language-servers = ["pylsp", "gpt"]
