[language-server.jdtls]
command = "jdtls"

[language-server.ruby-lsp]
command = "ruby-lsp"

[language-server.vscode-json-languageserver]
command = "vscode-json-languageserver"
args = ["--stdio"]

[language-server.typescript-language-server.config.plugins]
name = "@vue/typescript-plugin"
location = "/etc/profiles/per-user/okate/bin/typescript-language-server"
languages = ["vue"]

[[language]]
name = "vue"
language-servers = ["typescript-language-server"]

[[language]]
name = "java"
roots = ["build.gradle"]
language-servers = ["jdtls"]

[[language]]
name = "nix"
formatter = { command = "nixpkgs-fmt" }

[[language]]
name = "json"
language-servers = ["vscode-json-languageserver"]

# [[language]]
# name = "ruby"
# language-servers = ["ruby-lsp"]
