[general]
import = [
  "~/.config/alacritty/themes/sonokai.toml"
]

[window]
decorations = "full"

[font.normal]
family = "Hack Nerd Font"
style = "Light"

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"
